config:
  connectionStrings:
    identityService: #
    administrationService: #
    saasService: #
    productService: #
  dotnetEnv: Staging

# Seeded clients 
identityServerClients:
  angularRootUrl: #
  webRootUrl: #
  blazorRootUrl: #
  blazorServerRootUrl: #
  publicWebRootUrl: #
  webGatewayRootUrl: #
  publicWebGatewayRootUrl: #

image:
  repository: mycompanyname/rickandmortyapi-db-migrator
  tag: latest
  pullPolicy: IfNotPresent
  
env: {}  