config:
  selfUrl: # https://rickandmortyapi-st-identity
  corsOrigins: # https://rickandmortyapi-st-gateway-web,https://rickandmortyapi-st-gateway-public-web
  connectionStrings:
    identityService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://rickandmortyapi-st-authserver
    requireHttpsMetadata: # "false"
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

# Seeded clients 
identityServerClients:
  angularRootUrl: #
  webRootUrl: #
  blazorRootUrl: #
  blazorServerRootUrl: #
  publicWebRootUrl: #
  webGatewayRootUrl: #
  publicWebGatewayRootUrl: #

ingress:
  host: rickandmortyapi-st-identity
  tlsSecret: rickandmortyapi-tls

image:
  repository: mycompanyname/rickandmortyapi-service-identity
  tag: latest
  pullPolicy: IfNotPresent

env: {}
