config:
  selfUrl: # https://rickandmortyapi-st-product
  corsOrigins: #
  connectionStrings:
    productService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://rickandmortyapi-st-authserver
    requireHttpsMetadata: # "false"
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: rickandmortyapi-st-product
  tlsSecret: rickandmortyapi-tls

image:
  repository: mycompanyname/rickandmortyapi-service-product
  tag: latest
  pullPolicy: IfNotPresent

env: {}      